[package]
name = "common-operations"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin_hashes = "0.13.0"
hex-conservative = "0.2.0"
secp256k1 = "0.28.2"
bech32 = "0.11.0"
